apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: v55a3jfg8-python 
  janus-idp.io/tekton: v55a3jfg8-python
  backstage.io/kubernetes-id: v55a3jfg8-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: v55a3jfg8-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  